version: "3.9"

services:

  backend:
    build: .

    container_name: enterprise-rag-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - chroma_data:/app/chroma_storage

    restart: unless-stopped

volumes:
  chroma_data:
